name: Update Docker Images

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io

jobs:
  dockcross-build-push:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: linux-armhf-ubuntu18
          - name: linux-armhf-debian10
          - name: linux-armhf-debian11
          - name: linux-aarch64-debian11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/consider-it/cross-${{ matrix.name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
